### ISSUE TITLE
feat(powerup) Core. Pickup and state change.

### ISSUE THREAD

**Issue by mradionov** [dogballs/battle-city#7]
This issue is not refined, make sure to split it to sub-tasks when the logic will be clear and there will be no dependency blockers from other features.

Implement one of the power-ups, the most simple one first. It might require implementing a state machine for a tank.

Available powerups can be found here.
https://strategywiki.org/wiki/Battle_City/How_to_play#Power-Ups

**Comment by aailyin** [comment]
@mradionov What is it? Unclear description.

**Comment by mradionov** [comment]
@aailyin update the description.

**Comment by aailyin** [comment]
@mradionov Clear. Seems like it's a long-term issue.
